guid: "eb5212ba-b5e0-4aa4-a00c-9ab0cb4d1a5f"
name: "TMDB Trailers"
description: "Downloads movie trailers from TMDB for your media library"
overview: "This plugin automatically searches for and downloads movie trailers from The Movie Database (TMDB) API, organizing them alongside your movie files for enhanced viewing experience."
owner: "YourName"
category: "General"
imageUrl: ""
version: "1.0.0.0"
targetAbi: "10.8.13.0"
framework: "net8.0"
changelog: |
  ## 1.0.0
  - Initial release
  - TMDB trailer search and download
  - Automatic file organization
  - Configurable download settings
